import { createStitches } from "@stitches/react";
import {
  amber,
  amberDark,
  blue,
  blueDark,
  red,
  redDark,
  slate,
  slateDark,
} from "@radix-ui/colors";

export const {
  styled,
  css,
  globalCss,
  keyframes,
  getCssText,
  theme: lightTheme,
  createTheme,
  config,
} = createStitches({
  theme: {
    colors: {
      ...blue,
      ...slate,
      ...amber,
      ...red,

      // Accent "blue" color
      accent1: "$blue1",
      accent2: "$blue2",
      accent3: "$blue3",
      accent4: "$blue4",
      accent5: "$blue5",
      accent6: "$blue6",
      accent7: "$blue7",
      accent8: "$blue8",
      accent9: "$blue9",
      accent10: "$blue10",
      accent11: "$blue11",
      accent12: "$blue12",

      accentBg: "$accent1",
      accentBgSubtle: "$accent2",
      accentUIBg: "$accent3",
      accentUIBgHover: "$accent4",
      accentUIBgActive: "$accent5",
      accentBorderSubtle: "$accent6",
      accentBorder: "$accent7",
      accentBorderHover: "$accent8",
      accentBgSolid: "$accent9",
      accentBgSolidHover: "$accent10",
      accentTextSecondary: "$accent11",
      accentTextPrimary: "$accent12",

      // Warnings
      warning1: "$amber1",
      warning2: "$amber2",
      warning3: "$amber3",
      warning4: "$amber4",
      warning5: "$amber5",
      warning6: "$amber6",
      warning7: "$amber7",
      warning8: "$amber8",
      warning9: "$amber9",
      warning10: "$amber10",
      warning11: "$amber11",
      warning12: "$amber12",

      warningBg: "$warning1",
      warningBgSubtle: "$warning2",
      warningUIBg: "$warning3",
      warningUIBgHover: "$warning4",
      warningUIBgActive: "$warning5",
      warningBorderSubtle: "$warning6",
      warningBorder: "$warning7",
      warningBorderHover: "$warning8",
      warningBgSolid: "$warning9",
      warningBgSolidHover: "$warning10",
      warningTextSecondary: "$warning11",
      warningTextPrimary: "$warning12",

      // Errors
      error1: "$red1",
      error2: "$red2",
      error3: "$red3",
      error4: "$red4",
      error5: "$red5",
      error6: "$red6",
      error7: "$red7",
      error8: "$red8",
      error9: "$red9",
      error10: "$red10",
      error11: "$red11",
      error12: "$red12",

      errorBg: "$error1",
      errorBgSubtle: "$error2",
      errorUIBg: "$error3",
      errorUIBgHover: "$error4",
      errorUIBgActive: "$error5",
      errorBorderSubtle: "$error6",
      errorBorder: "$error7",
      errorBorderHover: "$error8",
      errorBgSolid: "$error9",
      errorBgSolidHover: "$error10",
      errorTextSecondary: "$error11",
      errorTextPrimary: "$error12",

      // Grays
      gray1: "$slate1",
      gray2: "$slate2",
      gray3: "$slate3",
      gray4: "$slate4",
      gray5: "$slate5",
      gray6: "$slate6",
      gray7: "$slate7",
      gray8: "$slate8",
      gray9: "$slate9",
      gray10: "$slate10",
      gray11: "$slate11",
      gray12: "$slate12",

      grayBgVoid: "#fff",
      grayBgSubtle: "$gray1",
      grayBg: "$gray2",
      grayUIBg: "$gray3",
      grayUIBgHover: "$gray4",
      grayUIBgActive: "$gray5",
      grayBorderSubtle: "$gray6",
      grayBorder: "$gray7",
      grayBorderHover: "$gray8",
      grayBgSolid: "$gray9",
      grayBgSolidHover: "$gray10",
      grayTextSecondary: "$gray11",
      grayTextPrimary: "$gray12",
    },
    fonts: {
      100: "Lato100",
      200: "Lato200",
      300: "Lato300",
      400: "Lato400",
      500: "Lato500",
      600: "Lato600",
      700: "Lato700",
      800: "Lato800",
      900: "Lato900",
    },
    fontSizes: {
      10: "0.625rem",
      12: "0.75rem",
      13: "0.8125rem",
      14: "0.875rem",
      15: "0.9375rem",
      16: "1rem",
      18: "1.125rem",
      20: "1.25rem",
      22: "1.375rem",
      24: "1.5rem",
      32: "2rem",
      40: "2.5rem",
      48: "3rem",
    },
  },
});

export const darkTheme = createTheme({
  colors: {
    ...blueDark,
    ...slateDark,
    ...amberDark,
    ...redDark,

    // Accent "blue" color
    accent1: "$blue1",
    accent2: "$blue2",
    accent3: "$blue3",
    accent4: "$blue4",
    accent5: "$blue5",
    accent6: "$blue6",
    accent7: "$blue7",
    accent8: "$blue8",
    accent9: "$blue9",
    accent10: "$blue10",
    accent11: "$blue11",
    accent12: "$blue12",

    accentBg: "$accent1",
    accentBgSubtle: "$accent2",
    accentUIBg: "$accent3",
    accentUIBgHover: "$accent4",
    accentUIBgActive: "$accent5",
    accentBorderSubtle: "$accent6",
    accentBorder: "$accent7",
    accentBorderHover: "$accent8",
    accentBgSolid: "$accent9",
    accentBgSolidHover: "$accent10",
    accentTextSecondary: "$accent11",
    accentTextPrimary: "$accent12",

    // Warnings
    warning1: "$amber1",
    warning2: "$amber2",
    warning3: "$amber3",
    warning4: "$amber4",
    warning5: "$amber5",
    warning6: "$amber6",
    warning7: "$amber7",
    warning8: "$amber8",
    warning9: "$amber9",
    warning10: "$amber10",
    warning11: "$amber11",
    warning12: "$amber12",

    warningBg: "$warning1",
    warningBgSubtle: "$warning2",
    warningUIBg: "$warning3",
    warningUIBgHover: "$warning4",
    warningUIBgActive: "$warning5",
    warningBorderSubtle: "$warning6",
    warningBorder: "$warning7",
    warningBorderHover: "$warning8",
    warningBgSolid: "$warning9",
    warningBgSolidHover: "$warning10",
    warningTextSecondary: "$warning11",
    warningTextPrimary: "$warning12",

    // Errors
    error1: "$red1",
    error2: "$red2",
    error3: "$red3",
    error4: "$red4",
    error5: "$red5",
    error6: "$red6",
    error7: "$red7",
    error8: "$red8",
    error9: "$red9",
    error10: "$red10",
    error11: "$red11",
    error12: "$red12",

    errorBg: "$error1",
    errorBgSubtle: "$error2",
    errorUIBg: "$error3",
    errorUIBgHover: "$error4",
    errorUIBgActive: "$error5",
    errorBorderSubtle: "$error6",
    errorBorder: "$error7",
    errorBorderHover: "$error8",
    errorBgSolid: "$error9",
    errorBgSolidHover: "$error10",
    errorTextSecondary: "$error11",
    errorTextPrimary: "$error12",

    // Grays
    gray1: "$slate1",
    gray2: "$slate2",
    gray3: "$slate3",
    gray4: "$slate4",
    gray5: "$slate5",
    gray6: "$slate6",
    gray7: "$slate7",
    gray8: "$slate8",
    gray9: "$slate9",
    gray10: "$slate10",
    gray11: "$slate11",
    gray12: "$slate12",

    grayBgVoid: "#000",
    grayBgSubtle: "$gray1",
    grayBg: "$gray2",
    grayUIBg: "$gray3",
    grayUIBgHover: "$gray4",
    grayUIBgActive: "$gray5",
    grayBorderSubtle: "$gray6",
    grayBorder: "$gray7",
    grayBorderHover: "$gray8",
    grayBgSolid: "$gray9",
    grayBgSolidHover: "$gray10",
    grayTextSecondary: "$gray11",
    grayTextPrimary: "$gray12",
  },
});
